In [1]:
import pandas as pd
import requests

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=<<API_KEY>>&language=en-US&page=1')

In [3]:
temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]

In [4]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,126.5761,8.956,1826
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,110.5352,8.723,30649
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,321.7840,8.710,3159
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,129.8917,8.692,5486
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,40.9483,8.687,23089

In [5]:
df = pd.DataFrame()

In [6]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1, 501):
  response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=<<API_KEY>>&language=en-US&page={}'.format(i))

  temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]

  df = pd.concat([df, temp_df], ignore_index=True)

In [8]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,126.5761,8.956,1826
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,110.5352,8.723,30649
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,321.7840,8.710,3159
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,129.8917,8.692,5486
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,40.9483,8.687,23089
...,...,...,...,...,...,...,...
9995,10375,D-Tox,A disgraced FBI agent with a drinking problem ...,2002-01-04,2.6135,5.578,721
9996,842934,Poker Face,A yearly high-stakes poker game between childh...,2022-11-16,3.8153,5.567,435
9997,419472,The Polka King,Local Pennsylvania polka legend Jan Lewan deve...,2017-01-22,1.3822,5.577,326
9998,301846,Howl,When passengers on a train are attacked by a c...,2015-10-01,2.0144,5.582,568
9999,82679,Fun Size,Wren's Halloween plans go awry when she's made...,2012-10-24,2.9241,5.567,449

In [9]:
df.shape

(10000, 7)

In [10]:
df.to_csv('movies.csv')